### ISSUE TITLE
可以对运行中的进程中的so的函数进行hook么？

### ISSUE THREAD

**Issue by yifannir** [Ayuto/DynamicHooks#10]
可以对运行中的进程中的so的函数进行hook么？

**Comment by Ayuto** [comment]
Yes, that's the idea of this library.

**Comment by yifannir** [comment]
can u give me some examples?thanks

**Comment by Ayuto** [comment]
You can find some examples of how to hook a function in the tests directory:
https://github.com/Ayuto/DynamicHooks/blob/master/tests/gcc_cdecl1.cpp

All you need is the address of the function. If it's a different process, you need to use DLL injection to attach your program to the so file. Then figure out the address and just hook it.
