### ISSUE TITLE
GetArgument<CBaseEntity*>(0) issues on post hook

### ISSUE THREAD

**Issue by roflmuffin** [Ayuto/DynamicHooks#8]
Hi there,

I am using this library inside of a Valve Server Plugin that is running on Windows, and I am using it to hook into BaseEntity functions such as "OnTakeDamage", "Weapon_Drop", etc.

When I am implementing this however it seems like the call to `GetArgument<CBaseEntity*>(0)` is fine on the pre hook, and the entity pointer I get back is a valid entity, however it seems in the post hook that this pointer is now invalid and no longer points to the entity.

I quickly modified the `ms_thiscall2.cpp` test file to assert that in the post hook the pointer is valid, so it must not be the libraries fault, but maybe the valve server doing something weird?

I know that this library is mainly used in Source.Python so I thought you might have an idea of why this could be happening or possibly some steps to debug this further?

**Comment by Ayuto** [comment]
Hey @roflmuffin,

there is an explanation of why this happens in the SP forum including a workaround.
https://forums.sourcepython.com/viewtopic.php?p=7542#p7542

I do have some ideas to "fix" it internally, but didn't have time to do that yet.

**Comment by roflmuffin** [comment]
Thanks mate, this is exactly the explanation I was looking for!
